spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sbr_demo
    username: root
    password: 194920
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true
